version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: flightdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flightservice:
    build: .
    container_name: flightservice
    restart: always
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: flightdb
    ports:
      - "5000:5000"

volumes:
  mysql_data:
